let
    Source = #table(
        type table [
            Month = date,
            MonthLabel = text,
            Client = text,
            Industry = text,
            ServiceType = text,
            RevenueBDT = Int64.Type,
            ProjectStatus = text,
            ReportTimeHrs = Int64.Type,
            Satisfaction = number,
            KPIAchievement = Int64.Type,
            NewLeads = Int64.Type,
            Conversions = Int64.Type,
            Region = text,
            TeamSize = Int64.Type,
            OnTime = text
        ],
        {
        {#date(2025, 3, 1), "Mar-25", "Adila Apparels", "Garments", "Custom Software Dev", 803539, "Active", 17, 3.5, 65, 14, 8, "Dhaka", 4, "Yes"},
        {#date(2025, 3, 1), "Mar-25", "Chai Break", "F&B", "AI & ML Solutions", 912411, "Completed", 17, 3.6, 63, 14, 7, "Dhaka", 3, "Yes"},
        {#date(2025, 3, 1), "Mar-25", "Fair Farm BD", "AgriTech", "Data Analytics", 965036, "Active", 17, 3.6, 62, 14, 6, "Dhaka", 4, "Yes"},
        {#date(2025, 3, 1), "Mar-25", "Infinabel", "E-commerce", "Digital Transformation", 1097331, "Active", 19, 3.6, 67, 12, 7, "Dhaka", 2, "Yes"},
        {#date(2025, 3, 1), "Mar-25", "Nodi Bangla", "Media", "Custom Software Dev", 1125531, "Completed", 19, 3.6, 61, 11, 4, "Chittagong", 3, "Yes"},
        {#date(2025, 3, 1), "Mar-25", "Robust Developments", "Real Estate", "Data Analytics", 1287946, "Active", 18, 3.5, 64, 13, 7, "Dhaka", 5, "Yes"},
        {#date(2025, 3, 1), "Mar-25", "Monoara Jahur", "Manufacturing", "AI & ML Solutions", 1409311, "Active", 19, 3.5, 61, 13, 6, "Dhaka", 3, "Yes"},
        {#date(2025, 3, 1), "Mar-25", "TechnoVate BD", "IT Services", "Digital Transformation", 1490732, "On Hold", 18, 3.6, 66, 14, 8, "Chittagong", 5, "Yes"},
        {#date(2025, 4, 1), "Apr-25", "Adila Apparels", "Garments", "Custom Software Dev", 1016803, "Active", 17, 3.8, 71, 15, 6, "Dhaka", 6, "Yes"},
        {#date(2025, 4, 1), "Apr-25", "Chai Break", "F&B", "AI & ML Solutions", 1045048, "Completed", 17, 3.7, 66, 12, 5, "Dhaka", 6, "Yes"},
        {#date(2025, 4, 1), "Apr-25", "Fair Farm BD", "AgriTech", "Data Analytics", 1097811, "Active", 18, 3.7, 65, 15, 8, "Dhaka", 2, "Yes"},
        {#date(2025, 4, 1), "Apr-25", "Infinabel", "E-commerce", "Digital Transformation", 1335688, "Active", 18, 3.8, 69, 13, 7, "Dhaka", 5, "Yes"},
        {#date(2025, 4, 1), "Apr-25", "Nodi Bangla", "Media", "Custom Software Dev", 1487683, "Completed", 17, 3.6, 71, 16, 9, "Chittagong", 4, "Yes"},
        {#date(2025, 4, 1), "Apr-25", "Robust Developments", "Real Estate", "Data Analytics", 1534894, "Active", 18, 3.6, 70, 14, 6, "Dhaka", 4, "Yes"},
        {#date(2025, 4, 1), "Apr-25", "Monoara Jahur", "Manufacturing", "AI & ML Solutions", 1639943, "Active", 18, 3.6, 68, 16, 9, "Dhaka", 2, "No"},
        {#date(2025, 4, 1), "Apr-25", "TechnoVate BD", "IT Services", "Digital Transformation", 1696079, "On Hold", 17, 3.6, 71, 16, 9, "Chittagong", 5, "Yes"},
        {#date(2025, 5, 1), "May-25", "Adila Apparels", "Garments", "Custom Software Dev", 1177942, "Active", 17, 3.8, 73, 16, 8, "Dhaka", 2, "Yes"},
        {#date(2025, 5, 1), "May-25", "Chai Break", "F&B", "AI & ML Solutions", 1154235, "Completed", 16, 3.9, 69, 16, 7, "Dhaka", 2, "Yes"},
        {#date(2025, 5, 1), "May-25", "Fair Farm BD", "AgriTech", "Data Analytics", 1314270, "Active", 17, 3.8, 71, 17, 7, "Dhaka", 4, "Yes"},
        {#date(2025, 5, 1), "May-25", "Infinabel", "E-commerce", "Digital Transformation", 1476231, "Active", 15, 3.8, 69, 16, 9, "Dhaka", 2, "Yes"},
        {#date(2025, 5, 1), "May-25", "Nodi Bangla", "Media", "Custom Software Dev", 1602951, "Completed", 16, 3.9, 71, 16, 8, "Chittagong", 4, "Yes"},
        {#date(2025, 5, 1), "May-25", "Robust Developments", "Real Estate", "Data Analytics", 1703927, "Active", 15, 3.9, 70, 13, 6, "Dhaka", 6, "Yes"},
        {#date(2025, 5, 1), "May-25", "Monoara Jahur", "Manufacturing", "AI & ML Solutions", 1845099, "Active", 15, 3.7, 69, 17, 8, "Dhaka", 5, "Yes"},
        {#date(2025, 5, 1), "May-25", "TechnoVate BD", "IT Services", "Digital Transformation", 1888263, "On Hold", 17, 3.7, 73, 17, 8, "Chittagong", 4, "Yes"},
        {#date(2025, 6, 1), "Jun-25", "Adila Apparels", "Garments", "Custom Software Dev", 1292273, "Active", 14, 3.8, 73, 19, 10, "Dhaka", 4, "Yes"},
        {#date(2025, 6, 1), "Jun-25", "Chai Break", "F&B", "AI & ML Solutions", 1315936, "Completed", 15, 3.9, 73, 18, 10, "Dhaka", 2, "Yes"},
        {#date(2025, 6, 1), "Jun-25", "Fair Farm BD", "AgriTech", "Data Analytics", 1500204, "Active", 16, 4.0, 71, 17, 7, "Dhaka", 3, "No"},
        {#date(2025, 6, 1), "Jun-25", "Infinabel", "E-commerce", "Digital Transformation", 1608013, "Active", 15, 4.0, 74, 18, 8, "Dhaka", 5, "Yes"},
        {#date(2025, 6, 1), "Jun-25", "Nodi Bangla", "Media", "Custom Software Dev", 1837378, "Completed", 16, 3.8, 71, 17, 9, "Chittagong", 4, "Yes"},
        {#date(2025, 6, 1), "Jun-25", "Robust Developments", "Real Estate", "Data Analytics", 2080199, "Active", 15, 4.0, 74, 17, 7, "Dhaka", 5, "Yes"},
        {#date(2025, 6, 1), "Jun-25", "Monoara Jahur", "Manufacturing", "AI & ML Solutions", 2142912, "Active", 15, 4.0, 71, 19, 9, "Dhaka", 3, "Yes"},
        {#date(2025, 6, 1), "Jun-25", "TechnoVate BD", "IT Services", "Digital Transformation", 2257990, "On Hold", 16, 3.9, 71, 18, 8, "Chittagong", 6, "No"},
        {#date(2025, 7, 1), "Jul-25", "Adila Apparels", "Garments", "Custom Software Dev", 1328056, "Active", 15, 4.0, 75, 19, 10, "Dhaka", 6, "Yes"},
        {#date(2025, 7, 1), "Jul-25", "Chai Break", "F&B", "AI & ML Solutions", 1564673, "Completed", 15, 4.0, 79, 16, 9, "Dhaka", 6, "Yes"},
        {#date(2025, 7, 1), "Jul-25", "Fair Farm BD", "AgriTech", "Data Analytics", 1661056, "Active", 15, 4.0, 75, 16, 8, "Dhaka", 6, "Yes"},
        {#date(2025, 7, 1), "Jul-25", "Infinabel", "E-commerce", "Digital Transformation", 2020827, "Active", 13, 4.1, 79, 16, 8, "Dhaka", 4, "Yes"},
        {#date(2025, 7, 1), "Jul-25", "Nodi Bangla", "Media", "Custom Software Dev", 2231239, "Completed", 15, 4.0, 81, 16, 9, "Chittagong", 2, "Yes"},
        {#date(2025, 7, 1), "Jul-25", "Robust Developments", "Real Estate", "Data Analytics", 2202257, "Active", 14, 4.0, 80, 17, 9, "Dhaka", 3, "Yes"},
        {#date(2025, 7, 1), "Jul-25", "Monoara Jahur", "Manufacturing", "AI & ML Solutions", 2313284, "Active", 14, 4.1, 75, 16, 7, "Dhaka", 6, "Yes"},
        {#date(2025, 7, 1), "Jul-25", "TechnoVate BD", "IT Services", "Digital Transformation", 2492129, "On Hold", 14, 4.1, 75, 20, 10, "Chittagong", 5, "No"},
        {#date(2025, 8, 1), "Aug-25", "Adila Apparels", "Garments", "Custom Software Dev", 1655409, "Active", 12, 4.0, 84, 21, 11, "Dhaka", 5, "Yes"},
        {#date(2025, 8, 1), "Aug-25", "Chai Break", "F&B", "AI & ML Solutions", 1791929, "Completed", 14, 4.1, 81, 18, 9, "Dhaka", 6, "Yes"},
        {#date(2025, 8, 1), "Aug-25", "Fair Farm BD", "AgriTech", "Data Analytics", 2065446, "Active", 13, 4.0, 82, 19, 9, "Dhaka", 4, "Yes"},
        {#date(2025, 8, 1), "Aug-25", "Infinabel", "E-commerce", "Digital Transformation", 2020580, "Active", 12, 4.2, 82, 21, 9, "Dhaka", 6, "Yes"},
        {#date(2025, 8, 1), "Aug-25", "Nodi Bangla", "Media", "Custom Software Dev", 2224054, "Completed", 13, 4.1, 85, 21, 9, "Chittagong", 3, "Yes"},
        {#date(2025, 8, 1), "Aug-25", "Robust Developments", "Real Estate", "Data Analytics", 2456389, "Active", 12, 4.1, 81, 21, 10, "Dhaka", 6, "No"},
        {#date(2025, 8, 1), "Aug-25", "Monoara Jahur", "Manufacturing", "AI & ML Solutions", 2580343, "Active", 13, 4.2, 79, 21, 9, "Dhaka", 3, "No"},
        {#date(2025, 8, 1), "Aug-25", "TechnoVate BD", "IT Services", "Digital Transformation", 2747391, "On Hold", 13, 4.0, 84, 18, 8, "Chittagong", 6, "Yes"},
        {#date(2025, 9, 1), "Sep-25", "Adila Apparels", "Garments", "Custom Software Dev", 1546714, "Active", 14, 4.1, 81, 19, 9, "Dhaka", 6, "Yes"},
        {#date(2025, 9, 1), "Sep-25", "Chai Break", "F&B", "AI & ML Solutions", 1567380, "Completed", 12, 4.0, 81, 17, 8, "Dhaka", 5, "Yes"},
        {#date(2025, 9, 1), "Sep-25", "Fair Farm BD", "AgriTech", "Data Analytics", 1751622, "Active", 13, 4.2, 81, 20, 9, "Dhaka", 6, "Yes"},
        {#date(2025, 9, 1), "Sep-25", "Infinabel", "E-commerce", "Digital Transformation", 1993492, "Active", 13, 4.2, 80, 18, 10, "Dhaka", 4, "No"},
        {#date(2025, 9, 1), "Sep-25", "Nodi Bangla", "Media", "Custom Software Dev", 2206306, "Completed", 12, 4.1, 81, 20, 11, "Chittagong", 5, "Yes"},
        {#date(2025, 9, 1), "Sep-25", "Robust Developments", "Real Estate", "Data Analytics", 2416718, "Active", 14, 4.2, 80, 18, 10, "Dhaka", 2, "Yes"},
        {#date(2025, 9, 1), "Sep-25", "Monoara Jahur", "Manufacturing", "AI & ML Solutions", 2690408, "Active", 14, 4.2, 79, 17, 7, "Dhaka", 4, "Yes"},
        {#date(2025, 9, 1), "Sep-25", "TechnoVate BD", "IT Services", "Digital Transformation", 2608156, "On Hold", 12, 4.0, 82, 18, 8, "Chittagong", 4, "No"},
        {#date(2025, 10, 1), "Oct-25", "Adila Apparels", "Garments", "Custom Software Dev", 1675019, "Active", 12, 4.3, 84, 21, 10, "Dhaka", 4, "Yes"},
        {#date(2025, 10, 1), "Oct-25", "Chai Break", "F&B", "AI & ML Solutions", 1859162, "Completed", 12, 4.3, 87, 22, 10, "Dhaka", 2, "No"},
        {#date(2025, 10, 1), "Oct-25", "Fair Farm BD", "AgriTech", "Data Analytics", 2236362, "Active", 11, 4.3, 87, 20, 11, "Dhaka", 5, "Yes"},
        {#date(2025, 10, 1), "Oct-25", "Infinabel", "E-commerce", "Digital Transformation", 2291299, "Active", 13, 4.3, 89, 24, 11, "Dhaka", 2, "Yes"},
        {#date(2025, 10, 1), "Oct-25", "Nodi Bangla", "Media", "Custom Software Dev", 2438984, "Completed", 12, 4.4, 88, 23, 10, "Chittagong", 4, "Yes"},
        {#date(2025, 10, 1), "Oct-25", "Robust Developments", "Real Estate", "Data Analytics", 2575865, "Active", 11, 4.4, 86, 20, 11, "Dhaka", 5, "Yes"},
        {#date(2025, 10, 1), "Oct-25", "Monoara Jahur", "Manufacturing", "AI & ML Solutions", 2993161, "Active", 13, 4.2, 87, 22, 10, "Dhaka", 6, "Yes"},
        {#date(2025, 10, 1), "Oct-25", "TechnoVate BD", "IT Services", "Digital Transformation", 3292594, "On Hold", 13, 4.4, 89, 24, 11, "Chittagong", 3, "Yes"},
        {#date(2025, 11, 1), "Nov-25", "Adila Apparels", "Garments", "Custom Software Dev", 1862412, "Active", 12, 4.4, 87, 23, 12, "Dhaka", 3, "Yes"},
        {#date(2025, 11, 1), "Nov-25", "Chai Break", "F&B", "AI & ML Solutions", 2219121, "Completed", 10, 4.3, 91, 26, 13, "Dhaka", 4, "Yes"},
        {#date(2025, 11, 1), "Nov-25", "Fair Farm BD", "AgriTech", "Data Analytics", 2408126, "Active", 10, 4.4, 90, 24, 11, "Dhaka", 5, "Yes"},
        {#date(2025, 11, 1), "Nov-25", "Infinabel", "E-commerce", "Digital Transformation", 2449081, "Active", 12, 4.5, 88, 25, 12, "Dhaka", 4, "Yes"},
        {#date(2025, 11, 1), "Nov-25", "Nodi Bangla", "Media", "Custom Software Dev", 2905781, "Completed", 11, 4.4, 86, 23, 12, "Chittagong", 4, "No"},
        {#date(2025, 11, 1), "Nov-25", "Robust Developments", "Real Estate", "Data Analytics", 2889452, "Active", 11, 4.4, 86, 25, 11, "Dhaka", 2, "Yes"},
        {#date(2025, 11, 1), "Nov-25", "Monoara Jahur", "Manufacturing", "AI & ML Solutions", 3327265, "Active", 11, 4.4, 88, 22, 10, "Dhaka", 6, "Yes"},
        {#date(2025, 11, 1), "Nov-25", "TechnoVate BD", "IT Services", "Digital Transformation", 3715580, "On Hold", 10, 4.5, 89, 26, 13, "Chittagong", 5, "Yes"},
        {#date(2025, 12, 1), "Dec-25", "Adila Apparels", "Garments", "Custom Software Dev", 1910205, "Active", 11, 4.5, 88, 25, 13, "Dhaka", 2, "Yes"},
        {#date(2025, 12, 1), "Dec-25", "Chai Break", "F&B", "AI & ML Solutions", 2342859, "Completed", 10, 4.5, 94, 24, 13, "Dhaka", 5, "Yes"},
        {#date(2025, 12, 1), "Dec-25", "Fair Farm BD", "AgriTech", "Data Analytics", 2382059, "Active", 9, 4.5, 91, 27, 13, "Dhaka", 5, "Yes"},
        {#date(2025, 12, 1), "Dec-25", "Infinabel", "E-commerce", "Digital Transformation", 2825317, "Active", 9, 4.6, 90, 24, 11, "Dhaka", 5, "Yes"},
        {#date(2025, 12, 1), "Dec-25", "Nodi Bangla", "Media", "Custom Software Dev", 3083894, "Completed", 9, 4.4, 90, 28, 14, "Chittagong", 6, "Yes"},
        {#date(2025, 12, 1), "Dec-25", "Robust Developments", "Real Estate", "Data Analytics", 3339520, "Active", 10, 4.4, 93, 25, 13, "Dhaka", 2, "No"},
        {#date(2025, 12, 1), "Dec-25", "Monoara Jahur", "Manufacturing", "AI & ML Solutions", 3682612, "Active", 10, 4.6, 88, 26, 12, "Dhaka", 2, "Yes"},
        {#date(2025, 12, 1), "Dec-25", "TechnoVate BD", "IT Services", "Digital Transformation", 4055602, "On Hold", 11, 4.5, 88, 25, 11, "Chittagong", 2, "Yes"},
        {#date(2026, 1, 1), "Jan-26", "Adila Apparels", "Garments", "Custom Software Dev", 1835153, "Active", 10, 4.7, 87, 27, 14, "Dhaka", 4, "Yes"},
        {#date(2026, 1, 1), "Jan-26", "Chai Break", "F&B", "AI & ML Solutions", 2248567, "Completed", 8, 4.6, 88, 24, 13, "Dhaka", 2, "Yes"},
        {#date(2026, 1, 1), "Jan-26", "Fair Farm BD", "AgriTech", "Data Analytics", 2321186, "Active", 10, 4.6, 90, 23, 10, "Dhaka", 3, "Yes"},
        {#date(2026, 1, 1), "Jan-26", "Infinabel", "E-commerce", "Digital Transformation", 2644981, "Active", 10, 4.6, 88, 25, 13, "Dhaka", 2, "Yes"},
        {#date(2026, 1, 1), "Jan-26", "Nodi Bangla", "Media", "Custom Software Dev", 2969660, "Completed", 8, 4.5, 89, 23, 10, "Chittagong", 6, "Yes"},
        {#date(2026, 1, 1), "Jan-26", "Robust Developments", "Real Estate", "Data Analytics", 3245290, "Active", 9, 4.7, 93, 26, 13, "Dhaka", 3, "Yes"},
        {#date(2026, 1, 1), "Jan-26", "Monoara Jahur", "Manufacturing", "AI & ML Solutions", 3497632, "Active", 10, 4.6, 93, 24, 11, "Dhaka", 5, "Yes"},
        {#date(2026, 1, 1), "Jan-26", "TechnoVate BD", "IT Services", "Digital Transformation", 3543233, "On Hold", 9, 4.7, 91, 27, 13, "Chittagong", 3, "Yes"},
        {#date(2026, 2, 1), "Feb-26", "Adila Apparels", "Garments", "Custom Software Dev", 2294659, "Active", 8, 4.8, 95, 27, 12, "Dhaka", 4, "Yes"},
        {#date(2026, 2, 1), "Feb-26", "Chai Break", "F&B", "AI & ML Solutions", 2361555, "Completed", 10, 4.7, 97, 28, 14, "Dhaka", 5, "Yes"},
        {#date(2026, 2, 1), "Feb-26", "Fair Farm BD", "AgriTech", "Data Analytics", 2589147, "Active", 8, 4.8, 93, 28, 13, "Dhaka", 6, "Yes"},
        {#date(2026, 2, 1), "Feb-26", "Infinabel", "E-commerce", "Digital Transformation", 2844692, "Active", 10, 4.8, 92, 29, 14, "Dhaka", 6, "Yes"},
        {#date(2026, 2, 1), "Feb-26", "Nodi Bangla", "Media", "Custom Software Dev", 3281378, "Completed", 8, 4.7, 92, 27, 12, "Chittagong", 6, "Yes"},
        {#date(2026, 2, 1), "Feb-26", "Robust Developments", "Real Estate", "Data Analytics", 3419515, "Active", 9, 4.8, 91, 28, 15, "Dhaka", 2, "Yes"},
        {#date(2026, 2, 1), "Feb-26", "Monoara Jahur", "Manufacturing", "AI & ML Solutions", 3648912, "Active", 8, 4.6, 93, 30, 16, "Dhaka", 3, "Yes"},
        {#date(2026, 2, 1), "Feb-26", "TechnoVate BD", "IT Services", "Digital Transformation", 4216367, "On Hold", 9, 4.7, 95, 27, 13, "Chittagong", 4, "Yes"}
        }
    ),
    #"Changed Type" = Table.TransformColumnTypes(Source,{
        {"Month", type date}, {"MonthLabel", type text}, {"Client", type text},
        {"Industry", type text}, {"ServiceType", type text}, {"RevenueBDT", Int64.Type},
        {"ProjectStatus", type text}, {"ReportTimeHrs", Int64.Type}, {"Satisfaction", type number},
        {"KPIAchievement", Int64.Type}, {"NewLeads", Int64.Type}, {"Conversions", Int64.Type},
        {"Region", type text}, {"TeamSize", Int64.Type}, {"OnTime", type text}
    })
in
    #"Changed Type"